# Generated by Django 4.0.5 on 2022-08-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsapdb',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='otherdb',
            name='Age',
            field=models.IntegerField(),
        ),
    ]
