# Generated by Django 4.0.5 on 2022-08-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0003_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='nsapdbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_no', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('pension_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='otherdbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
                ('income', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='nsapdb',
        ),
        migrations.DeleteModel(
            name='otherdb',
        ),
    ]
