# Generated by Django 4.0.5 on 2022-08-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0006_no_pension'),
    ]

    operations = [
        migrations.CreateModel(
            name='nopension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
                ('Dob', models.DateField()),
            ],
            options={
                'db_table': 'nopension',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='no_pension',
        ),
    ]
