# Generated by Django 4.0.5 on 2022-08-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0008_dbothers_delete_dbother'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbothers',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
