# Generated by Django 4.0.5 on 2022-08-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0009_alter_dbothers_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='dbnsaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_no', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('pension_id', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=6)),
                ('income', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='dbnsap',
        ),
    ]
