# Generated by Django 4.0.5 on 2022-08-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0011_db_nsaps_db_others_emp_delete_dbnsaps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='emp_mname',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
