# Generated by Django 4.0.5 on 2022-08-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0015_nsapdata_otherdata_delete_dbs_nsap_delete_dbs_other'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherdata',
            old_name='pl_family_id',
            new_name='bpl_family_id',
        ),
    ]
