# Generated by Django 4.0.5 on 2022-08-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0020_alter_other_data1_widow_alter_otherdata_widow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsapdata',
            name='widow',
            field=models.CharField(max_length=10),
        ),
    ]
