# Generated by Django 4.0.5 on 2022-08-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0021_alter_nsapdata_widow'),
    ]

    operations = [
        migrations.CreateModel(
            name='otherdata2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aadhar', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
                ('income', models.CharField(max_length=20)),
                ('Dob', models.DateField()),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=6)),
                ('status', models.IntegerField()),
                ('widow', models.CharField(max_length=10)),
                ('EPIC_id', models.CharField(max_length=10)),
                ('faulty', models.CharField(default='0', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='other_data1',
            name='disability',
        ),
    ]
