# Generated by Django 4.0.5 on 2022-08-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0022_otherdata2_remove_other_data1_disability'),
    ]

    operations = [
        migrations.CreateModel(
            name='otherdata1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
                ('Dob', models.DateField()),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=6)),
                ('gender', models.CharField(max_length=10)),
                ('status', models.IntegerField()),
                ('widow', models.CharField(max_length=3)),
                ('bpl_family_id', models.CharField(max_length=10)),
                ('EPIC_id', models.CharField(max_length=10)),
                ('faulty', models.CharField(default='0', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='other_data1',
        ),
        migrations.AlterField(
            model_name='nsapdata',
            name='widow',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='otherdata',
            name='widow',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='otherdata2',
            name='widow',
            field=models.CharField(max_length=3),
        ),
    ]
