# Generated by Django 4.0.5 on 2022-08-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0023_otherdata1_delete_other_data1_alter_nsapdata_widow_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='otherdata1',
            new_name='odata1',
        ),
        migrations.RenameModel(
            old_name='otherdata2',
            new_name='odata2',
        ),
    ]
