# Generated by Django 4.0.5 on 2022-08-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0024_rename_otherdata1_odata1_rename_otherdata2_odata2'),
    ]

    operations = [
        migrations.CreateModel(
            name='data1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
                ('Dob', models.DateField()),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=6)),
                ('gender', models.CharField(max_length=10)),
                ('status', models.IntegerField()),
                ('widow', models.CharField(max_length=3)),
                ('bpl_family_id', models.CharField(max_length=10)),
                ('faulty', models.CharField(default='0', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='data2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aadhar', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
                ('income', models.CharField(max_length=20)),
                ('Dob', models.DateField()),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=6)),
                ('status', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('widow', models.CharField(max_length=3)),
                ('EPIC_id', models.CharField(max_length=10)),
                ('faulty', models.CharField(default='0', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='odata1',
        ),
        migrations.DeleteModel(
            name='odata2',
        ),
    ]
