# Generated by Django 4.0.5 on 2022-08-26 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0025_data1_data2_delete_odata1_delete_odata2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data1',
        ),
        migrations.DeleteModel(
            name='data2',
        ),
    ]
